# Generated by Django 4.2.4 on 2024-04-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0013_alter_brand_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.DeleteModel(
            name="Subproduct",
        ),
    ]
