# Generated by Django 4.2.1 on 2023-05-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_address_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
    ]
