# Generated by Django 4.2.1 on 2023-06-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0007_razorpaydemo"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_paid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
