# Generated by Django 4.2.1 on 2023-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0015_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="line_1",
            field=models.CharField(max_length=250),
        ),
    ]
